### ISSUE TITLE
dataenum:1.5.0 is not compiling

### ISSUE THREAD

**Issue by tho-graf** [spotify/dataenum#41]
Hi there,

i tried to add you library in v 1.5.0. But unfortunately it didn't work. We also use auto-factory. When I added dataenum, the auto-factory still generated code, but java couldn't find it anymore and failed with `cannot find symbol X`.

I am no gradle expert at all but here are my infos:
We use gwt and compile with java 1.7.20 but have the sdk 1.17.

Downgrading to v 1.4.0 worked for me.

Do you have any idea?
Cheers Thomas

**Comment by pettermahlen** [comment]
I can think of two reasons: 
1. The library has been compiled with Java 8, so it may be that there is a bytecode version incompatibility when you're using 1.7. 
2. It could be related to changes made in #39 or #38, where some specific types were used whose locations might changed between Java versions. That at least made it harder to compile with later versions of Java (because files called tools.jar and rt.jar were removed and the way classes in those files are found was changed, IIRC).  

Can you try upgrading to 1.8? Or, alternatively, stick to 1.4.x in case you don't need the new features in 1.5.
